### ISSUE TITLE
SeamlessApiClient not resolving promise 

### ISSUE THREAD

**Issue by prabesh412** [mondaycom/monday-graphql-api#29]
I started using Monday GraphQL JS SDK (SeamlessApiClient) on our client side app and for some reason it's not resolving promise even tho the query is passing as 200.

![image](https://github.com/mondaycom/monday-graphql-api/assets/83510494/ccf59c49-a2e1-4de9-a56c-dc6182576643)

to clarify: seamlessApiClient.query is returning promise as pending even when it should have been success

**Comment by RomKadria** [comment]
Hey, are you running it from within an app from client side?

**Comment by prabesh412** [comment]
> Hey, are you running it from within an app from client side?

Hi, yes
I think this is already solved. you can close it 
thanks
