### ISSUE TITLE
Setting column values with createItemOp method

### ISSUE THREAD

**Issue by vladPovalii** [mondaycom/monday-graphql-api#40]
If I understand correctly `createItemOp` method doesn't have an argument to set column values except from `itemName`:

```javascript
type CreateItemOpMutationVariables = Exact<{
    boardId: Scalars['ID']['input'];
    groupId: Scalars['String']['input'];
    itemName: Scalars['String']['input'];
}>;
```

Can it be implemented by adding to this method `column_values` how it works in [API](https://developer.monday.com/api-reference/reference/items#create-an-item)? 

Or is there a better way to achieve this with SDK, aside from using `changeMultipleColumnValuesOp` after `createItemOp`?

**Comment by RomKadria** [comment]
Hey, you can create regular graphql query to support it :) 
the sdk show some basic usage, but for advanced cases writing graphql query is needed. 
The documentation should show you examples for it 
https://www.npmjs.com/package/@mondaydotcomorg/api

if you are useing typescript, you can interact with this to better help writing queries :) 
https://www.npmjs.com/package/@mondaydotcomorg/setup-api

**Comment by pinkasey** [comment]
Just noting that creating an item with values for its columns - is quite a basic scenario.
For instance -
I came to use this repo, exactly because graphQL is a bit hard to handle and I wanted a wrapper around it, to create a new item in a board.
